### ISSUE TITLE
To-Do til WIP test release

### ISSUE THREAD

**Issue by Gerold55** [Gerold55/WasteLands_Survival#1]
To-Do:
- [x] Adding a (random-geek's) crafting guide [cg_plus] to survival mode (https://forum.minetest.net/viewtopic.php?f=9&t=22385)
- [x] A working 2x2 crafting grid
- [x] Damage when trying to break a tree (any type of wood type) but you got no log
- [x] A workable 2 node furnace
- [x] A 100% workable thirst mod
- [ ] Adding ways to purify water
- [ ] A new player model
- [ ] Mob animations
- [ ] Ruins
- [ ] Textures for all other blocks implemented and replacement of textures

**Comment by MultiDragon** [comment]
The inventory I've done has the crafting guide builtin. Also 2x2 crafting grid works here (forgot to add 3x3 grid recipe though, feel free to adapt it to your game).
